import js from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";

export default [
  js.configs.recommended,
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        process: "readonly",
        global: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        performance: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        navigator: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        IntersectionObserver: "readonly",
        IntersectionObserverEntry: "readonly",
        ResizeObserver: "readonly",
        MediaQueryListEvent: "readonly",
        PerformanceObserver: "readonly",
        TextEncoder: "readonly",
        crypto: "readonly",
        require: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        NodeJS: "readonly",
        Window: "readonly",
        Document: "readonly",
        Storage: "readonly",
        DOMRect: "readonly",
        CSSStyleSheet: "readonly",
        CSSRule: "readonly",
        Blob: "readonly",
        File: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        WebSocket: "readonly",
        EventSource: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        ReadableStream: "readonly",
        WritableStream: "readonly",
        TransformStream: "readonly",
        MessageChannel: "readonly",
        MessagePort: "readonly",
        BroadcastChannel: "readonly",
        Worker: "readonly",
        SharedWorker: "readonly",
        ServiceWorker: "readonly",
        Notification: "readonly",
        PushManager: "readonly",
        PushSubscription: "readonly",
        caches: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      complexity: ["error", 10],
      "max-lines": ["error", { max: 300 }],
      "max-params": ["error", 4],
      "prefer-const": "error",
      "no-var": "error",
    },
  },
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/coverage/**",
      "**/test-results/**",
      "**/playwright-report/**",
      "**/tmp/**",
      "**/html/**",
      "**/dist/**",
      "**/build/**",
      "**/public/**",
      "**/*.config.js",
      "**/*.config.mjs",
      "**/*.config.ts",
      "**/next-env.d.ts",
      "**/types/**",
      "**/tests/**",
      "**/features/**",
      "**/scripts/**",
      "**/*.test.*",
      "**/*.spec.*",
      "**/*.mjs",
      "**/*.js",
      "**/vitest.*",
      "**/debug-*",
      "**/check-*",
    ],
  },
];
